/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sportsequipments;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.Color;

/**
 *
 * @author ELCOT
 */
public class s10 extends javax.swing.JFrame {
 int  ino,q;
String dobs,sql;
Float gst,samt,tamt,gstamt;
Date date;

    /**
     * Creates new form s10
     */
    public s10() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("REPORT PURCHASE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 380, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Enter Year");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 70, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 62, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 0, 204));
        b1.setText("Show");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsequipments/report.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 180, 160));

        L2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L2.setForeground(new java.awt.Color(0, 102, 204));
        L2.setText("Sports Equipment");
        L2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L2MouseClicked(evt);
            }
        });
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, -1));

        L3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L3.setForeground(new java.awt.Color(0, 102, 204));
        L3.setText("Purchase Company");
        L3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L3MouseClicked(evt);
            }
        });
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, -1));

        L4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L4.setForeground(new java.awt.Color(0, 102, 255));
        L4.setText("Purchase");
        L4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L4MouseClicked(evt);
            }
        });
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 60, -1));

        L5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L5.setForeground(new java.awt.Color(0, 102, 204));
        L5.setText("Sales");
        L5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L5MouseClicked(evt);
            }
        });
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 40, -1));

        L6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L6.setForeground(new java.awt.Color(0, 102, 204));
        L6.setText("Godown List");
        L6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L6MouseClicked(evt);
            }
        });
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 70, -1));

        L7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L7.setForeground(new java.awt.Color(0, 102, 204));
        L7.setText("Daily Sales Report");
        L7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L7MouseClicked(evt);
            }
        });
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 110, -1));

        L8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L8.setForeground(new java.awt.Color(0, 102, 204));
        L8.setText("Monthly Sales Report");
        L8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L8MouseClicked(evt);
            }
        });
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 130, -1));

        L9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L9.setForeground(new java.awt.Color(0, 102, 204));
        L9.setText("Home");
        L9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L9MouseClicked(evt);
            }
        });
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 40, -1));

        jLabel4.setBackground(new java.awt.Color(153, 0, 153));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 880, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
             
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select ino,gst,q,tamt,gstamt from purchase where year(date)=" +t1.getText() +"";
           // System.out.println(sql);
            rs=st.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            sql="select * from purchase where year(date)=" +t1.getText() + "";
            System.out.println(sql);
            rs=st.executeQuery(sql);
            
            }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void L2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseClicked
        // TODO add your handling code here:
        new s3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L2MouseClicked

    private void L3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseClicked
        // TODO add your handling code here:
        new s4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L3MouseClicked

    private void L4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseClicked
        // TODO add your handling code here:
        new s5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L4MouseClicked

    private void L5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseClicked
        // TODO add your handling code here:
        new s6().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L5MouseClicked

    private void L6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseClicked
        // TODO add your handling code here:
        new s7().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L6MouseClicked

    private void L7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseClicked
        // TODO add your handling code here:
        new s8().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L7MouseClicked

    private void L8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseClicked
        // TODO add your handling code here:
        new s9().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L8MouseClicked

    private void L9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
