/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sportsequipments;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Sri Maha Vishnu
 */
public class s3 extends javax.swing.JFrame {
    int hsnsac;
    String sname,dc,sql;
    Float pcost,scost,gst;
    

    /**
     * Creates new form s3
     */
    public s3() {
        initComponents();
        cbo1.removeAllItems();
        cbo1.addItem("Badminton");
        cbo1.addItem("Tennis");
        cbo1.addItem("Volley ball");
        cbo1.addItem("Cricket");
        cbo1.addItem("Hockey");
        clear();
        cbocall();
        getContentPane().setBackground(Color.WHITE);
         
    
    }
private void clear()
{
    t1.setText(null);
    t2.setText(null);
    t3.setText(null);
    t4.setText(null);
    t5.setText(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        cbo1 = new javax.swing.JComboBox();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        cbo2 = new javax.swing.JComboBox();
        L7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L5.setText("Sales cost");
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        L4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L4.setText("Purchase cost");
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        L2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L2.setText("Sports Name");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, 20));

        L1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L1.setText("HSN/SAC");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 70, -1));

        L6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L6.setText("GST %");
        L6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        L3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L3.setText("Desription");
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 70, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("SPORTS EQUIPMENT DETAILS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 40));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 50, -1));

        cbo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 80, -1));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 66, -1));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 66, -1));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 66, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 0, 255));
        b1.setText("SAVE");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 255));
        b3.setText("UPDATE");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 255));
        b2.setText("RESET");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        b4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 255));
        b4.setText("DELETE");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        cbo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo2ActionPerformed(evt);
            }
        });
        getContentPane().add(cbo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        L7.setText("Select HSN/SAC");
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsequipments/sports logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 178, -1));

        L8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L8.setForeground(new java.awt.Color(0, 102, 255));
        L8.setText("Purchase");
        L8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L8MouseClicked(evt);
            }
        });
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, -1));

        L9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L9.setForeground(new java.awt.Color(0, 102, 204));
        L9.setText("Sales");
        L9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L9MouseClicked(evt);
            }
        });
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, -1));

        L10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L10.setForeground(new java.awt.Color(0, 102, 204));
        L10.setText("Godown List");
        L10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L10MouseClicked(evt);
            }
        });
        getContentPane().add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, -1));

        L11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L11.setForeground(new java.awt.Color(0, 102, 204));
        L11.setText("Daily Sales Report");
        L11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L11MouseClicked(evt);
            }
        });
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 120, -1));

        L12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L12.setForeground(new java.awt.Color(0, 102, 204));
        L12.setText("Monthly Sales Report");
        L12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L12MouseClicked(evt);
            }
        });
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, -1));

        L13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L13.setForeground(new java.awt.Color(0, 102, 204));
        L13.setText("Report Purchase");
        L13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L13MouseClicked(evt);
            }
        });
        getContentPane().add(L13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, -1));

        L14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L14.setForeground(new java.awt.Color(0, 102, 204));
        L14.setText("Purchase Company");
        L14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L14MouseClicked(evt);
            }
        });
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, -1));

        L15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L15.setForeground(new java.awt.Color(0, 102, 204));
        L15.setText("Home");
        L15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L15MouseClicked(evt);
            }
        });
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 50, -1));

        jLabel4.setBackground(new java.awt.Color(153, 0, 153));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 740, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(t1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter HSNSAC");
            t1.requestFocus();
            return;
        }
        hsnsac=Integer.parseInt(t1.getText());
        sname="" +cbo1.getSelectedItem();
        dc=t2.getText();
        pcost=Float.parseFloat(t3.getText());
        scost=Float.parseFloat(t4.getText());
        gst=Float.parseFloat(t5.getText());
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from sdetails where hsnsac=" +hsnsac+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(rootPane, "HSNSAC already found");
                t1.requestFocus();
                return;
                
            }
            sql="insert into sdetails values(" +hsnsac+ ",'" +sname+ "','" +dc+ "'," +pcost+ "," +scost+ "," +gst+ ")";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Saved");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        cbocall();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        clear();
        t1.requestFocus();
    }//GEN-LAST:event_b2ActionPerformed

    private void cbo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo2ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from sdetails where hsnsac=" +cbo2.getSelectedItem()+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                t1.setText(rs.getString(1));
                cbo1.setSelectedItem(rs.getString(2));
                t2.setText(rs.getString(3));
                
                t3.setText(rs.getString(4));
                t4.setText(rs.getString(5));
                t5.setText(rs.getString(6));
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_cbo2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        hsnsac=Integer.parseInt(t1.getText());
        sname="" +cbo1.getSelectedItem();
        dc=t2.getText();
        pcost=Float.parseFloat(t3.getText());
        scost=Float.parseFloat(t4.getText());
        gst=Float.parseFloat(t5.getText());
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            sql="update sdetails set hsnsac=" +hsnsac+ ",sname='" +sname+ "',dc='" +dc+ "',pcost=" +pcost+ ",scost=" +scost+ ",gst=" +gst+ " where hsnsac=" +cbo2.getSelectedItem()+ "";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Updated");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        cbocall();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        int r=JOptionPane.showConfirmDialog(rootPane, "Do u want to delete","Delete",JOptionPane.YES_NO_OPTION);
        if(r==JOptionPane.YES_OPTION)
        {
       try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            sql="delete from sdetails where hsnsac=" +cbo2.getSelectedItem()+ "";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Deleted");
            clear();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        cbocall();
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void cbo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void L8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseClicked
        // TODO add your handling code here:
        new s5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L8MouseClicked

    private void L9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseClicked
        // TODO add your handling code here:
        new s6().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L9MouseClicked

    private void L10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L10MouseClicked
        // TODO add your handling code here:
        new s7().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L10MouseClicked

    private void L11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L11MouseClicked
        // TODO add your handling code here:
        new s8().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L11MouseClicked

    private void L12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L12MouseClicked
        // TODO add your handling code here:
        new s9().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L12MouseClicked

    private void L13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L13MouseClicked
        // TODO add your handling code here:
        new s10().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L13MouseClicked

    private void L14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L14MouseClicked
        // TODO add your handling code here:
        new s4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L14MouseClicked

    private void L15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L15MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L15MouseClicked
private void cbocall()
{   
    cbo2.removeAllItems();
    cbo2.addItem("0");
    try
    {
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
        Statement st=con.createStatement();
        ResultSet rs;
        sql="select *from sdetails";
        rs=st.executeQuery(sql);
        while(rs.next())
        {
            cbo2.addItem(rs.getString(1));
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L13;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JComboBox cbo1;
    private javax.swing.JComboBox cbo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
