/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sportsequipments;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Sri Maha Vishnu
 */
public class s4 extends javax.swing.JFrame {
int ccode;
String cname,address,cnumber,eid,cperson,gstno,sql;
    /**
     * Creates new form s4
     */
    public s4() {
        initComponents();
        clear();
        cbocall();
        getContentPane().setBackground(Color.WHITE);
    }
private void clear()
{
    t1.setText(null);
    t2.setText(null);
    t3.setText(null);
    t4.setText(null);
    t5.setText(null);
    t6.setText(null);
    t7.setText(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        cbo1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(153, 0, 51));
        L1.setText("PURCHASE COMPANY");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 430, -1));

        L2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L2.setText("Company Code");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 110, -1));

        L5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L5.setText("Contact no");
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 80, -1));

        L4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L4.setText("Address");
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 60, -1));

        L3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L3.setText("Name");
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 50, -1));

        L6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L6.setText("Email ID");
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 60, -1));

        L7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L7.setText("Contact person");
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 100, -1));

        L8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L8.setText("GST no");
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 50, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 80, 30));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 60, 30));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 110, 30));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 62, 30));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 100, 30));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 70, 30));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 70, 30));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 255));
        b1.setText("Save");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 255));
        b2.setText("Reset");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, 20));

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 255));
        b3.setText("Update");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        b4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 255));
        b4.setText("Delete");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));

        cbo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsequipments/purchase.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 200, 130));

        L9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L9.setForeground(new java.awt.Color(0, 102, 255));
        L9.setText("Purchase");
        L9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L9MouseClicked(evt);
            }
        });
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 60, -1));

        L10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L10.setForeground(new java.awt.Color(0, 102, 204));
        L10.setText("Sales");
        L10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L10MouseClicked(evt);
            }
        });
        getContentPane().add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 50, -1));

        L11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L11.setForeground(new java.awt.Color(0, 102, 204));
        L11.setText("Godown List");
        L11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L11MouseClicked(evt);
            }
        });
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, -1));

        L12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L12.setForeground(new java.awt.Color(0, 102, 204));
        L12.setText("Daily Sales Report");
        L12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L12MouseClicked(evt);
            }
        });
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 140, -1));

        L13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L13.setForeground(new java.awt.Color(0, 102, 204));
        L13.setText("Monthly Sales Report");
        L13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L13MouseClicked(evt);
            }
        });
        getContentPane().add(L13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 150, -1));

        L14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L14.setForeground(new java.awt.Color(0, 102, 204));
        L14.setText("Report Purchase");
        L14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L14MouseClicked(evt);
            }
        });
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, -1));

        L15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L15.setForeground(new java.awt.Color(0, 102, 204));
        L15.setText("Home");
        L15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L15MouseClicked(evt);
            }
        });
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 60, -1));

        L16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L16.setForeground(new java.awt.Color(0, 102, 204));
        L16.setText("Sports Equipment");
        L16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L16MouseClicked(evt);
            }
        });
        getContentPane().add(L16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, -1));

        jLabel4.setBackground(new java.awt.Color(153, 0, 153));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 0, 153));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 0, 153));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 790, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(t1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter ccode");
            t1.requestFocus();
            return;
        }
        ccode=Integer.parseInt(t1.getText());
        cname=t2.getText();
        address=t3.getText();
        cnumber=t4.getText();
        eid=t5.getText();
        cperson=t6.getText();
        gstno=t7.getText();
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from pcompany where ccode=" +ccode+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(rootPane, "ccode already found");
                t1.requestFocus();
                return;
            }
            sql="insert into pcompany values(" +ccode+ ",'" +cname+ "','" +address+ "','" +cnumber+ "','" +eid+ "','" +cperson+ "','" +gstno+ "')";
            System.out.println(sql);
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Saved");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        cbocall();
    }//GEN-LAST:event_b1ActionPerformed
private void cbocall()
{
    cbo1.removeAllItems();
    try
    {
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
        Statement st=con.createStatement();
        ResultSet rs;
        sql="select *from pcompany";
        rs=st.executeQuery(sql);
        while(rs.next())
        {
            cbo1.addItem(rs.getString(1));
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        clear();
        t1.requestFocus();
    }//GEN-LAST:event_b2ActionPerformed

    private void cbo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from pcompany where ccode=" +cbo1.getSelectedItem()+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                t1.setText(rs.getString(1));
                t2.setText(rs.getString(2));
                t3.setText(rs.getString(3));
                t4.setText(rs.getString(4));
                t5.setText(rs.getString(5));
                t6.setText(rs.getString(6));
                t7.setText(rs.getString(7));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
    }//GEN-LAST:event_cbo1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        ccode=Integer.parseInt(t1.getText());
        cname=t2.getText();
        address=t3.getText();
        cnumber=t4.getText();
        eid=t5.getText();
        cperson=t6.getText();
        gstno=t7.getText();
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="update pcompany set ccode=" +ccode+ ",cname='" +cname+ "',address='" +address+ "',cnumber='" +cnumber+ "',eid='" +eid+ "',cperson='" +cperson+ "',gstno='" +gstno+ "'where ccode=" +cbo1.getSelectedItem()+ "";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Updated");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        cbocall();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        int r=JOptionPane.showConfirmDialog(rootPane, "Do you want to delete","Delete",JOptionPane.YES_NO_OPTION);
        if (r==JOptionPane.YES_OPTION)
        {
            try
            {
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
                Statement st=con.createStatement();
                sql="delete from pcompany where ccode=" +cbo1.getSelectedItem()+ "";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "Deleted");
                clear();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
          cbocall();
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void L9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseClicked
        // TODO add your handling code here:
        new s5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L9MouseClicked

    private void L10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L10MouseClicked
        // TODO add your handling code here:
        new s6().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L10MouseClicked

    private void L11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L11MouseClicked
        // TODO add your handling code here:
        new s7().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L11MouseClicked

    private void L12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L12MouseClicked
        // TODO add your handling code here:
        new s8().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L12MouseClicked

    private void L13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L13MouseClicked
        // TODO add your handling code here:
        new s9().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L13MouseClicked

    private void L14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L14MouseClicked
        // TODO add your handling code here:
        new s10().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L14MouseClicked

    private void L15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L15MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L15MouseClicked

    private void L16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L16MouseClicked
        // TODO add your handling code here:
        new s3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L13;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L16;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JComboBox cbo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
