/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sportsequipments;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Sri Maha Vishnu
 */
public class s5 extends javax.swing.JFrame {
int ino,hsnsac,q,ccode;
String sname,dc,cname,address,cnumber,gstno,dobs,sql;
int inn;
Float pcost,gst,gstamt,amt,tamt;
Date date;
    /**
     * Creates new form s5
     */
    public s5() {
        initComponents();
        SimpleDateFormat format=new SimpleDateFormat ("dd-MM-yyyy");
        Date sdate=new Date();
        dobs=format.format(sdate);
        t2.setText(dobs);
    getContentPane().setBackground(Color.WHITE);
    hsncbocall();
    cbocall();
    clear();
    t1.setEditable(false);
    t2.setEditable(false);
    t3.setEditable(false);
    t4.setEditable(false);
    t5.setEditable(false);
    t6.setEditable(false);
    t10.setEditable(false);
    t11.setEditable(false);
    t12.setEditable(false);
    t13.setEditable(false);
    try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select max(ino) from purchase";
            System.out.println(sql);
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                inn=Integer.parseInt(rs.getString(1))+1;
                
               
                t1.setText(""+inn);
                 
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
    }
    
private void hsncbocall()
{
    cbo1.removeAllItems();
    try
    {
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
        Statement st=con.createStatement();
        ResultSet rs;
        sql="select *from sdetails";
        rs=st.executeQuery(sql);
        while(rs.next())
        {
            cbo1.addItem(rs.getString(1));
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}
private void cbocall()
{
    cbo2.removeAllItems();
    try
    {
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
        Statement st=con.createStatement();
        ResultSet rs;
        sql="select *from pcompany";
        rs=st.executeQuery(sql);
        while(rs.next())
        {
            cbo2.addItem(rs.getString(1));
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}
private void clear()
{
  t3.setText(null);
  t4.setText(null);
  t5.setText(null);
  t6.setText(null);
  t7.setText(null);
  t8.setText(null);
  t9.setText(null);
  t10.setText(null);
  t11.setText(null);
  t12.setText(null);
  t13.setText(null);
  t14.setText(null);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        cbo2 = new javax.swing.JComboBox();
        cbo1 = new javax.swing.JComboBox();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        L14 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        L18 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();
        L17 = new javax.swing.JLabel();
        L19 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        L20 = new javax.swing.JLabel();
        L21 = new javax.swing.JLabel();
        L22 = new javax.swing.JLabel();
        L23 = new javax.swing.JLabel();
        L24 = new javax.swing.JLabel();
        L25 = new javax.swing.JLabel();
        L26 = new javax.swing.JLabel();
        L27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(153, 0, 51));
        L1.setText("PURCHASE");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 220, -1));

        L2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L2.setText("Invoice no");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 70, 20));

        L3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L3.setForeground(new java.awt.Color(0, 153, 153));
        L3.setText("Equipment Details");
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        L4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L4.setText("Select HSN/SAC");
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 110, -1));

        L5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L5.setText("Purchase Cost");
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        L6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L6.setText("GST %");
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 60, -1));

        L7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L7.setText("Quantity");
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 70, -1));

        L8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L8.setText("Amount");
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 60, -1));

        L9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L9.setText("Total Amount");
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 90, -1));

        L10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L10.setText("Date");
        getContentPane().add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 40, 20));

        L12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L12.setText("Company Code");
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 100, -1));

        L11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L11.setForeground(new java.awt.Color(0, 153, 153));
        L11.setText("Purchase Company Details");
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        L13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L13.setText("GST Amount");
        getContentPane().add(L13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, 20));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 49, -1));

        cbo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo2ActionPerformed(evt);
            }
        });
        getContentPane().add(cbo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, 22));

        cbo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 255));
        b1.setText("calc");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, -1));

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 255));
        b2.setText("Save");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 255));
        b3.setText("Reset");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 80, -1));

        L14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L14.setText("Sports Name");
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, -1));

        L15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L15.setText("Description");
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 80, -1));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 90, -1));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 90, -1));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 90, -1));
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 90, -1));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 90, -1));
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 90, -1));

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 90, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 86, -1));
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 56, -1));

        L18.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L18.setText("Contact No");
        getContentPane().add(L18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 80, -1));

        L16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L16.setText("Company Name");
        getContentPane().add(L16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 100, -1));

        L17.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L17.setText("Address");
        getContentPane().add(L17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 60, -1));

        L19.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L19.setText("GST no");
        getContentPane().add(L19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 60, -1));
        getContentPane().add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 56, -1));
        getContentPane().add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 56, -1));
        getContentPane().add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 57, -1));
        getContentPane().add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 56, 28));

        L20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L20.setForeground(new java.awt.Color(0, 102, 255));
        L20.setText("Sales");
        L20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L20MouseClicked(evt);
            }
        });
        getContentPane().add(L20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 50, -1));

        L21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L21.setForeground(new java.awt.Color(0, 102, 204));
        L21.setText("Monthly sales report");
        L21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L21MouseClicked(evt);
            }
        });
        getContentPane().add(L21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, -1));

        L22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L22.setForeground(new java.awt.Color(0, 102, 204));
        L22.setText("Daily Sales Report");
        L22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L22MouseClicked(evt);
            }
        });
        getContentPane().add(L22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, -1));

        L23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L23.setForeground(new java.awt.Color(0, 102, 204));
        L23.setText("Home");
        L23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L23MouseClicked(evt);
            }
        });
        getContentPane().add(L23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 60, -1));

        L24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L24.setForeground(new java.awt.Color(0, 102, 204));
        L24.setText("Sports Equipment");
        L24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L24MouseClicked(evt);
            }
        });
        getContentPane().add(L24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, -1));

        L25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L25.setForeground(new java.awt.Color(0, 102, 204));
        L25.setText("Purchase Company");
        L25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L25MouseClicked(evt);
            }
        });
        getContentPane().add(L25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, -1));

        L26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L26.setForeground(new java.awt.Color(0, 102, 204));
        L26.setText("Godown List");
        L26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L26MouseClicked(evt);
            }
        });
        getContentPane().add(L26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, -1));

        L27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L27.setForeground(new java.awt.Color(0, 102, 204));
        L27.setText("Report Purchase");
        L27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L27MouseClicked(evt);
            }
        });
        getContentPane().add(L27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsequipments/item1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 150, 130));

        jLabel4.setBackground(new java.awt.Color(153, 0, 153));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 60, 900, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo1ActionPerformed
        // TODO add your handling code here:
         try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from sdetails where hsnsac=" +cbo1.getSelectedItem()+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                t3.setText(rs.getString(2));
                t4.setText(rs.getString(3));
                t5.setText(rs.getString(4));
                t6.setText(rs.getString(6));
                
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
      
                                         

    }//GEN-LAST:event_cbo1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
                                         

    }//GEN-LAST:event_t3ActionPerformed

    private void cbo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo2ActionPerformed
        // TODO add your handling code here:
                  try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from pcompany where ccode=" +cbo2.getSelectedItem()+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                t10.setText(rs.getString(2));
                t11.setText(rs.getString(3));
                t12.setText(rs.getString(4));
                t13.setText(rs.getString(7));
                
                
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       

    }//GEN-LAST:event_cbo2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        pcost=Float.parseFloat(t5.getText());
        q=Integer.parseInt(t7.getText());
        amt=pcost*q;
        gst=Float.parseFloat(t6.getText());
        gstamt=amt*gst/100;
        t8.setText(""+amt);
        tamt=amt+gstamt;
        t9.setText(""+tamt);
        t14.setText(""+gstamt);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         if(t7.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter Qty");
            t7.requestFocus();
            return;
        }
        ino=Integer.parseInt(t1.getText());
        dobs=t2.getText();
        hsnsac=Integer.parseInt("" +cbo1.getSelectedItem());
        sname=t3.getText();
        dc=t4.getText();
        pcost=Float.parseFloat(t5.getText());
        gst=Float.parseFloat(t6.getText());
        q=Integer.parseInt(t7.getText());
        amt=Float.parseFloat(t8.getText());
        tamt=Float.parseFloat(t9.getText());
        ccode=Integer.parseInt("" +cbo2.getSelectedItem());
        cname=t10.getText();
        address=t11.getText();
        cnumber=t12.getText();
        gstno=t13.getText();
        gstamt=Float.parseFloat(t14.getText());
        try
        {
        String sdate3=t2.getText();
        Date date3=new SimpleDateFormat("dd-MM-yyyy").parse(sdate3);
        SimpleDateFormat d3=new SimpleDateFormat("yyyy-MM-dd");
        dobs=d3.format(date3);
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
          
            
            String qry,qry1;
            int qty;
            
            qry="select * from godon where hsnsac=" + cbo1.getSelectedItem() + "";
            
            rs=st.executeQuery(qry);
            if (rs.next())
            {           
               qty=Integer.parseInt(rs.getString(4));
               qty=qty+q;
               
               qry1="update godon set q=" + qty + " where hsnsac=" + cbo1.getSelectedItem() + "";
               st.executeUpdate(qry1);
            }
            else
            {
            qry1="insert into godon values(" + hsnsac + ",'" + sname + "','" + dc + "'," + q + ")";
            st.executeUpdate(qry1);
            }
            
            
            sql="insert into purchase values(" + ino + "," + hsnsac + ",'" + sname + "','" + dc + "'," + pcost + "," + gst + "," + q + "," + amt + "," + tamt + ",'" + dobs + "'," + ccode + ",'" + cname + "','" + address + "','" + cnumber + "','" + gstno + "'," + gstamt + ")";
             //System.out.println(sql);
            st.executeUpdate(sql);
            
            
            
            JOptionPane.showMessageDialog(rootPane, "Data Saved");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
        
        
        
        
        
       hsncbocall();
    cbocall();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select max(ino) from purchase";
            System.out.println(sql);
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                inn=Integer.parseInt(rs.getString(1))+1;
                
               
                t1.setText(""+inn);
                 
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        clear();
        t1.requestFocus();
    
    }//GEN-LAST:event_b3ActionPerformed

    private void L20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L20MouseClicked
        // TODO add your handling code here:
        new s6().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L20MouseClicked

    private void L21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L21MouseClicked
        // TODO add your handling code here:
        new s9().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L21MouseClicked

    private void L22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L22MouseClicked
        // TODO add your handling code here:
        new s8().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L22MouseClicked

    private void L23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L23MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L23MouseClicked

    private void L24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L24MouseClicked
        // TODO add your handling code here:
        new s3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L24MouseClicked

    private void L25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L25MouseClicked
        // TODO add your handling code here:
        new s4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L25MouseClicked

    private void L26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L26MouseClicked
        // TODO add your handling code here:
        new s7().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L26MouseClicked

    private void L27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L27MouseClicked
        // TODO add your handling code here:
        new s10().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L27MouseClicked

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L13;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L16;
    private javax.swing.JLabel L17;
    private javax.swing.JLabel L18;
    private javax.swing.JLabel L19;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L21;
    private javax.swing.JLabel L22;
    private javax.swing.JLabel L23;
    private javax.swing.JLabel L24;
    private javax.swing.JLabel L25;
    private javax.swing.JLabel L26;
    private javax.swing.JLabel L27;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox cbo1;
    private javax.swing.JComboBox cbo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
