/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sportsequipments;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Sri Maha Vishnu
 */
public class s6 extends javax.swing.JFrame {
int bill,hsnsac,aqua,q;
String sname,dc,dobs,sql;
Float scost,gst,tamt,samt,gstamt;
Date date;
    /**
     * Creates new form s6
     */
    public s6() {
        initComponents();
        SimpleDateFormat format=new SimpleDateFormat ("dd-MM-yyyy");
        Date sdate=new Date();
        dobs=format.format(sdate);
        t2.setText(dobs);
    getContentPane().setBackground(Color.WHITE);
    hsncbocall();
    clear();
    t1.setEditable(false);
    t2.setEditable(false);
    t3.setEditable(false);
    t4.setEditable(false);
    t5.setEditable(false);
    t6.setEditable(false);
    t7.setEditable(false);
    try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select max(bill) from sale";
            System.out.println(sql);
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                bill=Integer.parseInt(rs.getString(1))+1;
                
               
                t1.setText(""+bill);
                 
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
    
    }
private void hsncbocall()
{
    cbo1.removeAllItems();
    try
    {
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
        Statement st=con.createStatement();
        ResultSet rs;
        sql="select *from sdetails";
        rs=st.executeQuery(sql);
        while(rs.next())
        {
            cbo1.addItem(rs.getString(1));
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}
private void clear()
{
  t3.setText(null);
  t4.setText(null);
  t5.setText(null);
  t6.setText(null);
  t7.setText(null);
  t8.setText(null);
  t9.setText(null);
  t10.setText(null);
  t11.setText(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        cbo1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();
        L17 = new javax.swing.JLabel();
        L18 = new javax.swing.JLabel();
        L19 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        L21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(153, 0, 51));
        L1.setText("SALES");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 130, -1));

        L2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L2.setText("Bill no");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 60, 20));

        L3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L3.setText("Select hsn/sac");
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, -1));

        L4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L4.setText("Sports Name");
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 90, -1));

        L5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L5.setText("Description");
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 80, -1));

        L6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L6.setText("Sales Cost");
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 70, -1));

        L7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L7.setText("GST %");
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 50, 28));

        L8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L8.setText("Available Quantity");
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 120, -1));

        L9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L9.setText("Quantity");
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 60, -1));

        L10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L10.setText("Sales Amount");
        getContentPane().add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 90, -1));

        L11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L11.setText("Date");
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, -1));

        L12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L12.setText("Total Amount");
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, 19));

        L13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        L13.setText("GST Amount");
        getContentPane().add(L13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, -1, 20));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 55, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 77, -1));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 77, -1));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 55, -1));

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 55, -1));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 55, -1));
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 55, -1));
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 80, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 72, -1));

        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 80, -1));

        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        getContentPane().add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 80, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 204));
        b1.setText("calc");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, -1, -1));

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 204));
        b2.setText("Save");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, -1, -1));

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 255));
        b3.setText("Reset");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, -1));

        cbo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsequipments/sales1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 267, -1));

        L14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L14.setForeground(new java.awt.Color(0, 102, 204));
        L14.setText("Monthly sales report");
        L14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L14MouseClicked(evt);
            }
        });
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        L15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L15.setForeground(new java.awt.Color(0, 102, 204));
        L15.setText("Daily Sales Report");
        L15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L15MouseClicked(evt);
            }
        });
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, -1));

        L16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L16.setForeground(new java.awt.Color(0, 102, 255));
        L16.setText("Purchase");
        L16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L16MouseClicked(evt);
            }
        });
        getContentPane().add(L16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        L17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L17.setForeground(new java.awt.Color(0, 102, 204));
        L17.setText("Home");
        L17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L17MouseClicked(evt);
            }
        });
        getContentPane().add(L17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 50, -1));

        L18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L18.setForeground(new java.awt.Color(0, 102, 204));
        L18.setText("Sports Equipment");
        L18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L18MouseClicked(evt);
            }
        });
        getContentPane().add(L18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, -1));

        L19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L19.setForeground(new java.awt.Color(0, 102, 204));
        L19.setText("Purchase Company");
        L19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L19MouseClicked(evt);
            }
        });
        getContentPane().add(L19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, -1));

        L20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L20.setForeground(new java.awt.Color(0, 102, 204));
        L20.setText("Godown List");
        L20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L20MouseClicked(evt);
            }
        });
        getContentPane().add(L20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, -1));

        L21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L21.setForeground(new java.awt.Color(0, 102, 204));
        L21.setText("Report Purchase");
        L21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L21MouseClicked(evt);
            }
        });
        getContentPane().add(L21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, -1));

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 60, 790, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(q>aqua)
        {
            JOptionPane.showMessageDialog(rootPane, "Quantity Excied");
            return;
        }
         if(t8.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter Qty");
            t8.requestFocus();
            return;
        }
        bill=Integer.parseInt(t1.getText());
        dobs=t2.getText();
        hsnsac=Integer.parseInt("" +cbo1.getSelectedItem());
        sname=t3.getText();
        dc=t4.getText();
        scost=Float.parseFloat(t5.getText());
        gst=Float.parseFloat(t6.getText());
       // aqua=Integer.parseInt(t7.getText());
        q=Integer.parseInt(t8.getText());
        samt=Float.parseFloat(t9.getText());
        tamt=Float.parseFloat(t10.getText());
        gstamt=Float.parseFloat(t11.getText());
        try
        {
        String sdate3=t2.getText();
        Date date3=new SimpleDateFormat("dd-MM-yyyy").parse(sdate3);
        SimpleDateFormat d3=new SimpleDateFormat("yyyy-MM-dd");
        dobs=d3.format(date3);
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            String qry,qry1;
            int qty;
            
            qry="select * from godon where hsnsac=" + cbo1.getSelectedItem() + "";
            
            rs=st.executeQuery(qry);
            if (rs.next())
            {           
               qty=Integer.parseInt(rs.getString(4));
               qty=qty-q;
               
               qry1="update godon set q=" + qty + " where hsnsac=" + cbo1.getSelectedItem() + "";
               st.executeUpdate(qry1);
            }
            sql="insert into sale values(" + bill + ",'" + dobs + "'," + hsnsac +",'" + sname + "','" + dc + "'," + scost + "," + gst + "," + q + "," + samt + "," + tamt + "," + gstamt + ")";
          System.out.println(sql);
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Saved");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       hsncbocall();
    
    
    }//GEN-LAST:event_b2ActionPerformed

    private void cbo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from sdetails where hsnsac=" +cbo1.getSelectedItem()+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                t3.setText(rs.getString(2));
                t4.setText(rs.getString(3));
                t5.setText(rs.getString(4));
                t6.setText(rs.getString(6));
                
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
         try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select *from godon where hsnsac=" +cbo1.getSelectedItem()+ "";
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                
                t7.setText(rs.getString(4));
                
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
      
                                         

    }//GEN-LAST:event_cbo1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        scost=Float.parseFloat(t5.getText());
        q=Integer.parseInt(t8.getText());
        samt=scost*q;
        gst=Float.parseFloat(t6.getText());
        gstamt=samt*gst/100;
        t9.setText(""+samt);
        tamt=samt+gstamt;
        t10.setText(""+tamt);
        t11.setText(""+gstamt);

    
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
            try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select max(bill) from sale";
            System.out.println(sql);
            rs=st.executeQuery(sql);
            if(rs.next())
            {
                bill=Integer.parseInt(rs.getString(1));
                bill=bill+1;
               
                t1.setText(""+bill);
                 
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    clear();
    t1.requestFocus();
    }//GEN-LAST:event_b3ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void L14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L14MouseClicked
        // TODO add your handling code here:
        new s9().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L14MouseClicked

    private void L15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L15MouseClicked
        // TODO add your handling code here:
        new s8().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L15MouseClicked

    private void L16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L16MouseClicked
        // TODO add your handling code here:
        new s5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L16MouseClicked

    private void L17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L17MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L17MouseClicked

    private void L18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L18MouseClicked
        // TODO add your handling code here:
        new s3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L18MouseClicked

    private void L19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L19MouseClicked
        // TODO add your handling code here:
        new s4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L19MouseClicked

    private void L20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L20MouseClicked
        // TODO add your handling code here:
        new s7().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L20MouseClicked

    private void L21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L21MouseClicked
        // TODO add your handling code here:
        new s10().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L13;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L16;
    private javax.swing.JLabel L17;
    private javax.swing.JLabel L18;
    private javax.swing.JLabel L19;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L21;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox cbo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
