/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sportsequipments;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.Color;
/**
 *
 * @author Sri Maha Vishnu
 */
public class s7 extends javax.swing.JFrame {
int hsnsac,q;
String sname,dc,sql;
    /**
     * Creates new form s7
     */
    public s7() {
        initComponents();
        cbo1.removeAllItems();
        cbo1.addItem("111");
        cbo1.addItem("124");
        cbo1.addItem("126");
        cbo2.removeAllItems();
        cbo2.addItem("Badminton");
        cbo2.addItem("Tennis");
        cbo2.addItem("Volley ball");
        cbo2.addItem("Cricket");
        cbo2.addItem("Hockey");
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        L1 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JButton();
        cbo1 = new javax.swing.JComboBox();
        cbo2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L17 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(153, 0, 51));
        L1.setText("GODOWN LIST");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 290, -1));

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        r1.setText("All");
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        r2.setText("Select HSN/SAC");
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        r3.setText("Equipment");
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 255));
        b1.setText("Show");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        cbo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        cbo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo2ActionPerformed(evt);
            }
        });
        getContentPane().add(cbo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, 101));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsequipments/godown.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 160, 140));

        L11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L11.setForeground(new java.awt.Color(0, 102, 204));
        L11.setText("Monthly sales report");
        L11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L11MouseClicked(evt);
            }
        });
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, -1));

        L12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L12.setForeground(new java.awt.Color(0, 102, 204));
        L12.setText("Daily Sales Report");
        L12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L12MouseClicked(evt);
            }
        });
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, -1));

        L9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L9.setForeground(new java.awt.Color(0, 102, 255));
        L9.setText("Purchase");
        L9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L9MouseClicked(evt);
            }
        });
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, -1));

        L17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L17.setForeground(new java.awt.Color(0, 102, 204));
        L17.setText("Home");
        L17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L17MouseClicked(evt);
            }
        });
        getContentPane().add(L17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 50, -1));

        L16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L16.setForeground(new java.awt.Color(0, 102, 204));
        L16.setText("Sports Equipmednt");
        L16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L16MouseClicked(evt);
            }
        });
        getContentPane().add(L16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, -1));

        L15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L15.setForeground(new java.awt.Color(0, 102, 204));
        L15.setText("Purchase Company");
        L15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L15MouseClicked(evt);
            }
        });
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, -1));

        L10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L10.setForeground(new java.awt.Color(0, 102, 204));
        L10.setText("Sales");
        L10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L10MouseClicked(evt);
            }
        });
        getContentPane().add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 50, -1));

        L14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L14.setForeground(new java.awt.Color(0, 102, 204));
        L14.setText("Report Purchase");
        L14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L14MouseClicked(evt);
            }
        });
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, -1));

        jLabel2.setBackground(new java.awt.Color(153, 0, 153));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, 750, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            if(r1.isSelected())
            {
                sql="select * from godon";
            }
            else if(r2.isSelected())
            {
                sql="select * from godon where hsnsac=" + cbo1.getSelectedItem() + "";
            }
            else if(r3.isSelected())
            {
                sql="select * from godon where sname='" + cbo2.getSelectedItem() + "'";
            }
            System.out.println(sql);
            rs=st.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
            }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void L11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L11MouseClicked
        // TODO add your handling code here:
        new s9().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L11MouseClicked

    private void L12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L12MouseClicked
        // TODO add your handling code here:
        new s8().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L12MouseClicked

    private void L9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseClicked
        // TODO add your handling code here:
        new s5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L9MouseClicked

    private void L17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L17MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L17MouseClicked

    private void L16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L16MouseClicked
        // TODO add your handling code here:
        new s3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L16MouseClicked

    private void L15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L15MouseClicked
        // TODO add your handling code here:
        new s4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L15MouseClicked

    private void L10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L10MouseClicked
        // TODO add your handling code here:
        new s6().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L10MouseClicked

    private void L14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L14MouseClicked
        // TODO add your handling code here:
        new s10().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L16;
    private javax.swing.JLabel L17;
    private javax.swing.JLabel L9;
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbo1;
    private javax.swing.JComboBox cbo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    // End of variables declaration//GEN-END:variables
}
