/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sportsequipments;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.Color;

/**
 *
 * @author ELCOT
 */
public class s9 extends javax.swing.JFrame {
int bill,q;
String dobs,sql;
Float gst,samt,tamt,gstamt;
Date date;

    /**
     * Creates new form s9
     */
    public s9() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
       L1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("MONTHLY SALES REPORT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 490, 30));

        jLabel2.setText("Enter year");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel3.setText("Month");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        b1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 204));
        b1.setText("Show");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel4.setText("Sales Amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        L1.setText("lable");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 59, -1));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 100, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 100, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, 290));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sportsequipments/month logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 195, -1));

        L16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L16.setForeground(new java.awt.Color(0, 102, 204));
        L16.setText("Sports Equipment");
        L16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L16MouseClicked(evt);
            }
        });
        getContentPane().add(L16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, -1));

        L15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L15.setForeground(new java.awt.Color(0, 102, 204));
        L15.setText("Purchase Company");
        L15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L15MouseClicked(evt);
            }
        });
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, -1));

        L14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L14.setForeground(new java.awt.Color(0, 102, 204));
        L14.setText("Report Purchase");
        L14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L14MouseClicked(evt);
            }
        });
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 110, -1));

        L10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L10.setForeground(new java.awt.Color(0, 102, 204));
        L10.setText("Sales");
        L10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L10MouseClicked(evt);
            }
        });
        getContentPane().add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 50, -1));

        L11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L11.setForeground(new java.awt.Color(0, 102, 204));
        L11.setText("Godown List");
        L11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L11MouseClicked(evt);
            }
        });
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 80, -1));

        L12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L12.setForeground(new java.awt.Color(0, 102, 204));
        L12.setText("Daily Sales Report");
        L12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L12MouseClicked(evt);
            }
        });
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, -1));

        L9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L9.setForeground(new java.awt.Color(51, 0, 255));
        L9.setText("Purchase");
        L9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L9MouseClicked(evt);
            }
        });
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 70, -1));

        L17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        L17.setForeground(new java.awt.Color(0, 102, 204));
        L17.setText("Home");
        L17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L17MouseClicked(evt);
            }
        });
        getContentPane().add(L17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 50, -1));

        jLabel6.setBackground(new java.awt.Color(153, 0, 153));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 920, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
             
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sports","root","");
            Statement st=con.createStatement();
            ResultSet rs;
            sql="select bill,gst,q,tamt,gstamt from sale where year(date)=" +t1.getText() +" and month(date)=" + t2.getText();
           // System.out.println(sql);
            rs=st.executeQuery(sql);
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            sql="select * from sale where year(date)=" +t1.getText() + " and month(date)=" + t2.getText();
            System.out.println(sql);
            rs=st.executeQuery(sql);
            float amt;
            amt=0;
            
            while(rs.next())
            {
                amt=amt+Float.parseFloat(rs.getString(10));
                    
                        
                    }
            L1.setText(""+amt);
            
            }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void L16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L16MouseClicked
        // TODO add your handling code here:
        new s3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L16MouseClicked

    private void L15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L15MouseClicked
        // TODO add your handling code here:
        new s4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L15MouseClicked

    private void L14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L14MouseClicked
        // TODO add your handling code here:
        new s10().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L14MouseClicked

    private void L10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L10MouseClicked
        // TODO add your handling code here:
        new s6().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L10MouseClicked

    private void L11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L11MouseClicked
        // TODO add your handling code here:
        new s7().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L11MouseClicked

    private void L12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L12MouseClicked
        // TODO add your handling code here:
        new s8().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L12MouseClicked

    private void L9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseClicked
        // TODO add your handling code here:
        new s5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L9MouseClicked

    private void L17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L17MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_L17MouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L16;
    private javax.swing.JLabel L17;
    private javax.swing.JLabel L9;
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
